package quiz20200320;
public enum Format {
	// More of the list from https://en.wikipedia.org/wiki/List_of_radio_stations_in_New_York
	// Note you cannot start with a digit, we started it an underline (above)	
	_1950S_OLDIES ("1950s oldies"), 
	_80S_HITS ("80s Hits"),
	AAA_PROGRESSIVE_BLUES_RnB_JAZZ_FOLK ("AAA, progressive, blues, R&B, jazz & folk"),
	AC_TALK ("Ac/talk"), 
	ACTIVE_ROCK ("Active rock"), 
	ADULT_ALBUM_ALTERNATIVE ("Adult album alternative"),
	ADULT_ALBUM_ALTERNATIVE_TALK ("Adult album alternative/talk"),
	ADULT_CONTEMPORARY ("Adult contemporary"), 
	ADULT_CONTEMPORARY_NEWS ("Adult contemporary & news"),
	ADULT_HITS ("Adult hits"),
	ADULT_STANDARDS ("Adult standards"),
	ALBUM_ADULT_ALTERNATIVE ("Album adult alternative"), 
	ALBUM_ORIENTED_ROCK ("Album-oriented rock"),
	ALTERNATIVE ("Alternative"), 
	ALTERNATIVE_RADIO ("Alternative radio"), 
	ALTERNATIVE_ROCK ("Alternative rock"),
	AMERICANA ("Americana"),
	BOLLYWOOD_MUSIC ("Bollywood (indian) music"), 
	CAMPUS_RADIO ("Campus radio"), 
	CATHOLIC ("Catholic"), 
	CHR ("Chr"),
	CHR_COLLEGE ("Chr/college"), 
	CHRISTIAN ("Christian"), 
	CHRISTIAN_CONTEMPORARY_K_LOVE ("Christian contemporary (k-love)"), 
	CHRISTIAN_WORSHIP_AIR1 ("Christian worship (air1)"),
	CLASSIC_COUNTRY ("Classic Country"), CLASSIC_HITS ("Classic Hits"),
	CLASSIC_HIP_HOP ("Classic hip-hop"),
	CLASSIC_HITS_1980S ("Classic hits/1980s"), 
	CLASSIC_ROCK ("Classic Rock"),
	CLASSICAL ("Classical"), CHRISTIAN_FAMILY_LIFE_NETWORK ("Christian (Family Life Network)"),
	CLASSICAL_MUSIC_AND_NEWS ("Classical music and news"),
	COLLEGE ("College"), 
	COMMUNITY_RADIO ("Community radio"), 
	CONTEMPORARY_CHRISTIAN ("Contemporary christian"),
	CONTEMPORARY_CHRISTIAN_K_LOVE ("Contemporary christian (k-love)"),
	EDUCATIONAL ("Educational"), 
	ETHNIC ("Ethnic"), 
	ETHNIC_CHINESE_SPANISH ("Ethnic/chinese & spanish"),
	ETHNIC_GREEK ("Ethnic/Greek"),
	FREEFORM ("Freeform"), 
	FREEFORM_ALTERNATIVE ("Freeform/alternative"),
	FULL_SERVICE ("Full-service"),
	FULL_SERVICE_CLASSIC_HITS ("Full-service/classic hits"),
	FULL_SERVICE_NEWS_TALK ("Full service/news/talk"), 
	HOT_AC ("Hot ac"), 
	HOT_ADULT_CONTEMPORARY ("Hot adult contemporary"), 
	INDEPENDENT ("Independent"), 
	JAZZ_ETHNIC ("Jazz, ethnic"), 
	JAZZ_MIXED ("Jazz/mixed"),
	MAINSTREAM_JAZZ ("Mainstream jazz"), 
	MODERN_ROCK ("Modern rock"), 
	NEWS ("News"), 
	NEWS_RADIO ("News radio"),
	NEWS_TALK ("News/talk"), 
	NEWS_TALK_INFORMATION ("News/talk information"), 
	NEWS_TALK_RADIO ("News/talk radio"), 
	NPR ("NPR"), 
	OLDIES ("Oldies"), 
	OTHER ("Other"),
	POP_ROCK_RAP ("Pop, rock, rap"),
	PUBLIC_RADIO ("Public Radio"), 
	PUBLIC_RADIO_ADULT_ALBUM_ALTERNATIVE ("Public radio, adult album alternative"),
	REAL_COUNTRY ("Real country"),
	REGIONAL_MEXICAN ("Regional mexican"),
	RELIGIOUS ("Religious"), 
	RELIGIOUS_BROADCASTING ("Religious broadcasting"), 
	RELIGIOUS_CATHOLIC ("Religious (catholic)"), 
	RELIGIOUS_CSN_INTERNATIONAL ("Religious (csn international)"),
	RELIGIOUS_TEACHING ("Religious teaching"),
	RHYTHMIC_AC_LEANING_TOP_40_CHR ("Rhythmic ac-leaning top 40 (chr)"),
	RHYTHMIC_CONTEMPORARY ("Rhythmic contemporary"), 
	ROCK ("Rock"),
	ROCK_CLASSIC_ROCK ("Rock/classic rock"),
	SMOOTH_JAZZ_BLUES ("Smooth jazz/blues"),
	SOFT_ADULT_CONTEMPORARY ("Soft adult contemporary"),
	SOFT_ADULT_CONTEMPORARY_OLDIES ("Soft adult contemporary/oldies)"),
	SPANISH_ADULT_CONTEMPORARY ("Spanish/adult contemporary"), 
	SPANISH_HITS ("Spanish hits"), 
	SPANISH_LANGUAGE_TROPICAL ("Spanish-language/tropical"),
	SPANISH_NEWS_TALK ("Spanish News and Talk"),
	SPANISH_RELIGIOUS ("Spanish religious"), 
	SPANISH_SPORTS ("Spanish sports"),
	SPORTS ("Sports"), 
	SPORTS_RADIO ("Sports radio"), 
	TALK_RADIO ("Talk radio"), 
	TALK_RADIO_DAYTIME_OLDIES_NIGHTS_WEEKENDS ("Talk radio (daytime) & oldies (nights/weekends)"),
	TOP40_JAZZ_SPORTS_NEWS_LATINO_RAP ("Top 40, jazz, sports, news, latino, rap"),
	URBAN_ADULT_CONTEMPORARY ("Urban adult contemporary"),
	URBAN_CONTEMPORARY ("Urban contemporary"), 
	URBAN_CONTEMPORARY_GOSPEL ("Urban contemporary gospel"), 
	VARIETY_HITS ("Variety hits"), 
	VARIETY_PACIFICA ("Variety/pacifica");
	
	private String format;
	private Format(String aFormat) {
		format = aFormat;
	}	
	public String toString() {
		return format;
	}	
}
